site_name: MatsuriDayo
site_url: https://matsuridayo.github.io/
repo_url: https://github.com/MatsuriDayo/matsuridayo.github.io
edit_uri: ""
repo_name: 文档
copyright: CC BY-SA 4.0
theme:
  name: material
  logo: https://matsuridayo.github.io/assets/images/matsuri1.jpg
  palette:
    - scheme: default
      primary: indigo
      toggle:
        icon: material/brightness-7
    - scheme: slate
      primary: black
      toggle:
        icon: material/brightness-4
markdown_extensions:
  - pymdownx.magiclink
  - admonition
  - pymdownx.details
  - pymdownx.superfences
nav:
  - 首页: index.md
  - 下载: download.md
  - Android-配置: nb4a-configuration.md
  - Android-路由: nb4a-route.md
  - Android-FAQ: nb4a-faq.md
  - Android-白话文-国内外分流: nb4a-bhw-domestic.md
  - Android-插件: nb4a-plugin.md
  - PC-配置: n-configuration.md
  - PC-自定义核心: n-extra_core.md
  - PC-FAQ: n-faq.md
